### PR TITLE
Migrate to yarp::dev::IRGBDSensor interface

### LINKED ISSUE #83: Drop old OpenNI2 interfaces, adopt IRGBDSensor
YARP devel has discontinued support for several devices, affecting Kinect/OpenNI2 devices currently used in this repo. This means that the `yarp/dev/IOpenNI2DeviceDriver.h` header (as well as `yarp/dev/IKinectDeviceDriver.h`, by the way) is no longer installed: [YARP v3.0.0 Release Notes (unreleased)](https://github.com/robotology/yarp/blob/3136ec4854cda8426827f5b4f39bfd1eaad65d5d/doc/release/v3_0_0.md#libraries).

There is a replacement, though. Client apps must switch to the [`yarp::dev::RGBDSensorClient`](http://www.yarp.it/classyarp_1_1dev_1_1RGBDSensorClient.html) device and the [`yarp::dev::IRGBDSensor`](http://www.yarp.it/classyarp_1_1dev_1_1IRGBDSensor.html) interface, which should be barely invasive on our end (the vision repo). Real camera devices are now wrapped by [`yarp::dev::depthCameraDriver`](http://www.yarp.it/classyarp_1_1dev_1_1depthCameraDriver.html) (goes by the .ini name of *depthCamera*).

### PR DESCRIPTION
**Pull request by PeterBowman**
Closes #83. Notes:

* Minimum required YARP version established at ~~2.3.68~~ 2.3.70.
* Mind this hack: https://github.com/roboticslab-uc3m/vision/issues/83#issuecomment-381096322.
* Tested on Kinect v1 + *colorRegionDetection* and *haarDetection* apps. While working with a Kinect v2 device, be aware of #85.

---

(Edit: TODO list moved to https://github.com/roboticslab-uc3m/vision/issues/89.)

### CODE REVIEW

**Comment by PeterBowman** [comment]
I totally overlooked @jgvictores's contribs at https://github.com/roboticslab-uc3m/vision/commit/97430a53d80319c0b5b3f906d14b769875946a85. Note to self: cherry pick and/or apply changes on current working branch.

**Comment by PeterBowman** [comment]
> fetch intrinsic/extrinsic camera parameters from device via IRGBDSensor's getters?

I mean, things like:

https://github.com/roboticslab-uc3m/vision/blob/549cea19a744353276c11f55e491265763edb79c/programs/colorRegionDetection/main.cpp#L32-L39

Now, such parameters belong to (are required by) the *depthCamera* device and should be loaded via .ini file: http://www.yarp.it/classyarp_1_1dev_1_1depthCameraDriver.html#details.

**Comment by jgvictores** [comment]
As commented at #85:
- In the deprecated OpenNI2 device, we had `--printVideoModes` to see both RGB and Depth modes. Modes set resolution and framerate, and may vary among device and even firmware.
- For TEO, we fixed the RGB and Depth mode parameters for the specific sensor+firmware so resolution would match: https://github.com/roboticslab-uc3m/teo-configuration-files/blob/b37b041ddcfddfe1347cfb4d5c22737d0aa069d2/share/teoBase/scripts/teoBase.xml#L36

Relevant to the [above comment](#issuecomment-381121548):
- Old `cx_x` (I guess new `principalPointX`) are 1/2*resolutionX. Same goes for Y. Not sure about other intrinsic parameters, but anyway, in practical terms it means we must match out parameters with the specific device mode setting (ending up with a set of pre-defined `.ini` configutation files for each device+mode setting).

**Comment by jgvictores** [comment]
> fetch intrinsic/extrinsic camera parameters from device via IRGBDSensor's getters?

Just understood this better. You are completely right.

Since their are now getters, there is no sync issue anymore, as parameters can directly be fetched from the device.

Yes, definitely remove them as settable params from the config on the vision processing side.

**Comment by PeterBowman** [comment]
Config settings for old `OpenNI2DeviceServer` device: http://wiki.icub.org/wiki/OpenNI2.

**Comment by PeterBowman** [comment]
Note: YARP 3 introduces `RGBDParamParser` (https://github.com/robotology/yarp/pull/1634).

**Comment by PeterBowman** [comment]
@jgvictores this PR involves a bug (high priority) and several improvements (low priority). Since the bug has been solved quite a while ago, would you mind if we merge this code? Then, I'll split the TODO list into one or more separate issues and open another one concerning the ugly delay hack.

**Edit:** also, can we delete [this branch](https://github.com/roboticslab-uc3m/vision/commit/97430a53d80319c0b5b3f906d14b769875946a85)?

**Comment by jgvictores** [comment]
> Edit: also, can we delete this branch?

Yes!

**Comment by PeterBowman** [comment]
> Then, I'll split the TODO list into one or more separate issues and open another one concerning the ugly delay hack.

* https://github.com/roboticslab-uc3m/vision/issues/88 (ugly hack)
* https://github.com/roboticslab-uc3m/vision/issues/89 (further improvements)

**Pull request merged**
